### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by BasharAG** [joshboldt/gofin#2]
After installing dependencies through NPM, I was able to run scraper.sh, but I got the following error:

```
~/gofin$ ./scraper.sh
Tickers scraped 🍕
open: invalid option -- 'a'
Usage: open [OPTIONS] -- command

This utility help you to start a program on a new virtual terminal (VT).

Options:
  -c, --console=NUM   use the given VT number;
  -e, --exec          execute the command, without forking;
  -f, --force         force opening a VT without checking;
  -l, --login         make the command a login shell;
  -u, --user          figure out the owner of the current VT;
  -s, --switch        switch to the new VT;
  -w, --wait          wait for command to complete;
  -v, --verbose       print a message for each action;
  -V, --version       print program version and exit;
  -h, --help          output a brief help message.
```

**Comment by joshboldt** [comment]
Hi! This isn't close to finished yet, just up here for sake of keeping track of things. 

The fix to your error is that you need to build the script. If you are on Mac, run the command `chmod u+x scraper.sh` and it should build it. After that, you can run `./scraper.sh`. Alternatively, you can skip this step and simply run `node scraper.js` if you have node installed. It will deposit the `tickers.json` in the same directory.
